data = {
    "alwar": {
        "place": "Alwar",
        "state": "Rajasthan",
        "places": "Bala Quila, City Palace, Sariska Tiger Reserve, Moosi Maharani ki Chhatri, Siliserh Lake, Vinay Vilas Mahal",
        "hotels": "Some notable hotels in Alwar include ABC Hotel, XYZ Resort, PQR Inn",
        "details": "Alwar, located in the state of Rajasthan, is a city known for its rich history and cultural heritage. The city is home to magnificent historical landmarks such as Bala Quila and City Palace, offering a glimpse into the royal past. Nature enthusiasts can explore the Sariska Tiger Reserve, while architecture lovers can visit the beautiful Moosi Maharani ki Chhatri and Vinay Vilas Mahal. The serene Siliserh Lake is also a popular spot for relaxation."
    },
    "bharatpur": {
        "place": "Bharatpur",
        "state": "Rajasthan",
        "places": "Keoladeo National Park, Lohagarh Fort, Bharatpur Palace, Government Museum",
        "hotels": "MNO Heritage Hotel, XYZ Palace Resort, LMN Inn",
        "details": "Bharatpur, situated in the state of Rajasthan, is a city known for its rich cultural heritage and biodiversity. It was founded by Maharaja Suraj Mal in 1733. The city is renowned for Keoladeo National Park, a UNESCO World Heritage Site, and various historical landmarks that reflect its royal past.",
    },
    "bikaner": {
        "place": "Bikaner",
        "state": "Rajasthan",
        "places": "Junagarh Fort, Karni Mata Temple, Lalgarh Palace, National Research Centre on Camel",
        "hotels": "ABC Heritage Hotel, XYZ Palace Resort, LMN Inn",
        "details": "Bikaner, situated in the heart of the Thar Desert, is a vibrant city in the state of Rajasthan. Founded by Rao Bika in 1488, the city is known for its rich cultural heritage, impressive architecture, and unique attractions.",
    },
    "chittorgarh": {
        "place": "Chittorgarh",
        "state": "Rajasthan",
        "places": "Chittorgarh Fort, Padmini Palace",
        "hotels": "PQR Heritage Hotel, LMN Palace Resort, XYZ Inn",
        "details": "Chittorgarh, a city in Rajasthan, is known for its rich history, majestic forts, and tales of valor. Founded in the 7th century by Chitrangada Mori, Chittorgarh has been witness to many historic events and is a testament to the Rajputana glory.",
    },
    "garadia_mahadev": {
        "place": "Garadia Mahadev",
        "state": "Rajasthan",
        "places": "Garadia Mahadev Viewpoint",
        "hotels": "Limited accommodation options nearby",
        "details": "Garadia Mahadev is a picturesque viewpoint in the state of Rajasthan, known for its stunning views and natural beauty. The main attraction is the viewpoint that provides breathtaking panoramic views of the surrounding landscape.",
    },
    "jaipur": {
        "place": "Jaipur",
        "state": "Rajasthan",
        "places": "Hawa Mahal, City Palace, Jantar Mantar, Amer Fort, Nahargarh Fort, Jaigarh Fort, Jal Mahal, Albert Hall Museum",
        "hotels": "ABC Royal Hotel, XYZ Heritage Resort, LMN Inn",
        "details": "Jaipur, also known as the Pink City, is the capital of Rajasthan and a city steeped in history and culture. Founded by Maharaja Sawai Jai Singh II in 1727, Jaipur is known for its vibrant architecture, rich heritage, and bustling markets.",
    },
    "jaisalmer": {
        "place": "Jaisalmer",
        "state": "Rajasthan",
        "places": "Jaisalmer Fort, Patwon Ki Haveli, Salim Singh Ki Haveli, Gadisar Lake, Sam Sand Dunes, Kuldhara Village",
        "hotels": "LMN Desert Resort, XYZ Heritage Hotel, ABC Inn",
        "details": "Jaisalmer, known as the Golden City, is a mesmerizing destination in the heart of the Thar Desert. Founded by Maharawal Jaisal Singh in 1156 AD, the city is famous for its golden sandstone architecture, forts, and vibrant culture.",
    },
    "jodhpur": {
        "place": "Jodhpur",
        "state": "Rajasthan",
        "places": "Mehrangarh Fort, Jaswant Thada, Umaid Bhawan Palace, Mandore Gardens, Clock Tower and Sardar Market",
        "hotels": "LMN Royal Hotel, XYZ Heritage Resort, ABC Inn",
        "details": "Jodhpur, known as the Blue City, is a historic city in Rajasthan with a rich cultural heritage. Founded by Rao Jodha in 1459, the city is famous for its blue-painted houses, magnificent forts, and vibrant markets.",
    },
    "kumbhalgarh": {
        "place": "Kumbhalgarh",
        "state": "Rajasthan",
        "places": "Kumbhalgarh Fort, Badal Mahal, Neelkanth Mahadev Temple, Kumbhalgarh Wildlife Sanctuary",
        "hotels": "PQR Heritage Hotel, XYZ Retreat, LMN Inn",
        "details": "Kumbhalgarh, situated in the Aravalli Range, is renowned for its majestic fortress and historical significance. The primary attraction, Kumbhalgarh Fort, is a Mewar fortress on the westerly range of Aravalli Hills.",
    },
    "mount_abu": {
        "place": "Mount Abu",
        "state": "Rajasthan",
        "places": "Dilwara Temples, Nakki Lake, Guru Shikhar, Mount Abu Wildlife Sanctuary, Sunset Point",
        "hotels": "LMN Hill Resort, XYZ Retreat, ABC Inn",
        "details": "Mount Abu, the only hill station in Rajasthan, is a serene retreat in the Aravalli Range. Famous for its cool climate, scenic beauty, and historic sites, it attracts visitors seeking a peaceful escape from the heat of the plains.",
    },
    "neemrana": {
        "place": "Neemrana",
        "state": "Rajasthan",
        "places": "Neemrana Fort Palace, Baori, Vinay Vilas Mahal, Sariska National Park",
        "hotels": "Neemrana Fort Palace, XYZ Heritage Hotel, ABC Retreat",
        "details": "Neemrana, located in the Alwar district of Rajasthan, is renowned for its heritage and the majestic Neemrana Fort Palace. The town offers a blend of history, architecture, and natural beauty, making it a popular destination for tourists.",
    },
    "pushkar": {
        "place": "Pushkar",
        "state": "Rajasthan",
        "places": "Pushkar Lake, Brahma Temple, Savitri Temple, Pushkar Camel Fair",
        "hotels": "LMN Lakeview Hotel, XYZ Heritage Resort, ABC Inn",
        "details": "Pushkar, a holy town nestled around Pushkar Lake, is known for its spiritual significance and vibrant culture. It attracts pilgrims, tourists, and traders from around the world, especially during the annual Pushkar Camel Fair.",
    },
    "ranakpur": {
        "place": "Ranakpur",
        "state": "Rajasthan",
        "places": "Ranakpur Jain Temple, Surya Narayan Temple, Muchhal Mahavir Temple, Sadri, Kumbhalgarh Wildlife Sanctuary",
        "hotels": "LMN Palace Hotel, XYZ Heritage Resort, ABC Retreat",
        "details": "Ranakpur, located in the Aravalli Range, is renowned for its intricately carved marble Jain temples. The town is a significant pilgrimage site and offers a tranquil atmosphere amidst natural beauty.",
    },
    "ranthambore": {
        "place": "Ranthambore",
        "state": "Rajasthan",
        "places": "Ranthambore National Park, Ranthambore Fort, Surwal Lake, Padam Talao, Malik Talao",
        "hotels": "LMN Safari Lodge, XYZ Jungle Retreat, ABC Luxury Camp",
        "details": "Ranthambore is a renowned destination in Rajasthan, known for its wildlife and the Ranthambore National Park. The park is home to diverse flora and fauna, including the elusive Bengal tiger, making it a popular choice for wildlife enthusiasts.",
    },
    "udaipur": {
        "place": "Udaipur",
        "state": "Rajasthan",
        "places": "City Palace, Lake Pichola, Jag Mandir, Jagdish Temple, Saheliyon Ki Bari",
        "hotels": "LMN Lake Palace, XYZ Heritage Hotel, ABC Inn",
        "details": "Udaipur, the 'City of Lakes,' is a romantic and picturesque destination in Rajasthan. Known for its stunning palaces, serene lakes, and vibrant culture, Udaipur attracts tourists seeking a blend of history and natural beauty.",
    },


#utharkhand
    "auli": {
        "place": "Auli",
        "state": "Uttarakhand",
        "places": "Auli Ski Resort, Gurso Bugyal, Chattrakund, Kwani Bugyal, Joshimath",
        "hotels": "LMN Ski Lodge, XYZ Mountain Retreat, ABC Guesthouse",
        "details": "Auli is a charming hill station nestled in the Garhwal Himalayas of Uttarakhand. Known for its scenic beauty, meadows, and snow-covered landscapes, Auli is a popular destination for skiing enthusiasts and nature lovers.",
    },
    "badrinath": {
        "place": "Badrinath",
        "state": "Uttarakhand",
        "places": "Badrinath Temple, Tapt Kund, Neelkanth Peak, Charanpaduka, Vasudhara Falls",
        "hotels": "LMN Pilgrim Inn, XYZ Heritage Lodge, ABC Guest House",
        "details": "Badrinath, situated in the Chamoli district of Uttarakhand, is one of the holiest towns for Hindus. It is renowned for the Badrinath Temple, dedicated to Lord Vishnu, and is part of the Char Dham Yatra pilgrimage circuit.",
    },
    "chopta": {
        "place": "Chopta",
        "state": "Uttarakhand",
        "places": "Tungnath Temple, Chandrashila, Deoria Tal, Kanchula Korak Musk Deer Sanctuary",
        "hotels": "LMN Himalayan Retreat, XYZ Eco Lodge, ABC Nature Camp",
        "details": "Chopta, also known as the 'Mini Switzerland of Uttarakhand,' is a charming hill station situated in the Garhwal region. It offers breathtaking views of the Himalayas and is a popular destination for nature lovers and trekkers.",
    },
    "dehradun": {
        "place": "Dehradun",
        "state": "Uttarakhand",
        "places": "Robber's Cave, Forest Research Institute, Sahastradhara, Tapkeshwar Temple, Mindrolling Monastery",
        "hotels": "LMN Grand Hotel, XYZ Boutique Stay, ABC Budget Inn",
        "details": "Dehradun, situated in the Doon Valley, is a picturesque city surrounded by the Shivalik Range. It serves as the gateway to several tourist destinations in Uttarakhand and offers a mix of natural beauty, historical sites, and modern amenities.",
    },
    "gangotri": {
        "place": "Gangotri",
        "state": "Uttarakhand",
        "places": "Gangotri Temple, Bhagirathi Shila, Pandava Gufa, Gaumukh, Surya Kund",
        "hotels": "LMN Pilgrim Residency, XYZ Guest House, ABC Retreat",
        "details": "Gangotri is a revered pilgrimage destination situated in the Garhwal Himalayas. It holds immense religious significance as the origin point of the sacred river Ganges. Pilgrims visit Gangotri as part of the Char Dham Yatra to seek blessings.",
    },
    "haridwar": {
        "place": "Haridwar",
        "state": "Uttarakhand",
        "places": "Har Ki Pauri, Mansa Devi Temple, Chandi Devi Temple, Ganga Aarti, Maya Devi Temple",
        "hotels": "LMN Riverside Retreat, XYZ Heritage Hotel, ABC Budget Inn",
        "details": "Haridwar, situated on the banks of the Ganges River, is one of the seven holiest places in Hinduism. It is known for its religious ceremonies, ghats, and the Ganga Aarti, attracting pilgrims and tourists from around the world.",
    },
    "jim_corbett": {
        "place": "Jim Corbett National Park",
        "state": "Uttarakhand",
        "zones": "Dhikala Zone, Bijrani Zone, Jhirna Zone, Durga Devi Zone, Dhela Zone",
        "wildlife": "Bengal Tiger, Indian Elephant, Leopard, Himalayan Black Bear, Crocodile",
        "birds": "Great Hornbill, Red Junglefowl, Crested Serpent Eagle, Kingfishers, Peafowl",
        "hotels": "LMN Jungle Lodge, XYZ Wildlife Resort, ABC Riverside Camp",
        "details": "Jim Corbett National Park is India's oldest national park and a haven for wildlife enthusiasts. Established in 1936, it is named after Jim Corbett, a renowned conservationist. The park is known for its rich biodiversity and is a popular destination for wildlife safaris.",
    },
    "kedarnath": {
        "place": "Kedarnath",
        "state": "Uttarakhand",
        "places": "Kedarnath Temple, Bhairavnath Temple, Shankaracharya Samadhi, Chorabari Tal, Vasuki Tal",
        "hotels": "LMN Pilgrim Resthouse, XYZ Heritage Lodge, ABC Budget Inn",
        "details": "Kedarnath, situated in the Garhwal Himalayas, is a significant pilgrimage site for Hindus. It is one of the Char Dham Yatra destinations and holds immense religious importance. The town is known for the ancient Kedarnath Temple dedicated to Lord Shiva.",
    },
    "lansdowne": {
        "place": "Lansdowne",
        "state": "Uttarakhand",
        "places": "Tip-in-Top Point, Bhulla Lake, St. Mary's Church, Darwan Singh Regimental Museum, Tarkeshwar Mahadev Temple",
        "hotels": "LMN Hillside Retreat, XYZ Cottage Stay, ABC Luxury Resort",
        "details": "Lansdowne, named after the Viceroy of India, Lord Lansdowne, is a serene and picturesque hill station. Nestled in the Garhwal Himalayas, Lansdowne offers tranquility, colonial charm, and panoramic views of the surrounding mountains.",
    },
    "mukteshwar": {
        "place": "Mukteshwar",
        "state": "Uttarakhand",
        "places": "Mukteshwar Temple, Chauli Ki Jali, Indian Veterinary Research Institute, Bhalu Gaad Waterfall, Sitla",
        "details": "Mukteshwar, perched at an elevation of about 2,285 meters, is a tranquil town known for its Himalayan views and apple orchards. The town is named after the Mukteshwar Temple, dedicated to Lord Shiva, and offers a peaceful getaway in the Kumaon region.",
    },
    "mussoorie": {
        "place": "Mussoorie",
        "state": "Uttarakhand",
        "places": "Gun Hill, Kempty Falls, The Mall Road, Camel's Back Road, Company Garden",
        "hotels": "LMN Hillview Resort, XYZ Boutique Hotel, ABC Mountain Retreat",
        "details": "Mussoorie, often referred to as the 'Queen of Hills,' is a charming hill station nestled in the Garhwal Himalayas. Known for its pleasant climate and stunning views, Mussoorie attracts tourists with its colonial architecture, lush landscapes, and various attractions.",
    },
    "nainital": {
        "place": "Nainital",
        "state": "Uttarakhand",
        "places": "Naini Lake, Naina Devi Temple, Snow View Point, The Mall Road, Tiffin Top",
        "hotels": "LMN Lakeside Retreat, XYZ Heritage Hotel, ABC Hillview Inn",
        "details": "Nainital, situated around the famous Naini Lake, is a picturesque hill station surrounded by mountains. Known for its captivating beauty, pleasant weather, and numerous lakes, Nainital is a popular destination for tourists seeking a peaceful retreat.",
    },
    "rishikesh": {
        "place": "Rishikesh",
        "state": "Uttarakhand",
        "places": "Triveni Ghat, Parmarth Niketan, Laxman Jhula, The Beatles Ashram, Shivpuri",
        "hotels": "LMN Riverside Retreat, XYZ Yoga Inn, ABC Adventure Camp",
        "details": "Rishikesh, located on the banks of the Ganges River, is a spiritual hub and adventure destination. Known for its ashrams, temples, and yoga centers, Rishikesh attracts seekers of spirituality and adventure enthusiasts from around the world.",
    },
    "valley_of_flowers": {
        "place": "Valley of Flowers",
        "state": "Uttarakhand",
		"hotels":"the tattva","camp valley of flowers","hotel himalayan holidays",
        "details": "The Valley of Flowers, a UNESCO World Heritage Site, is a mesmerizing alpine meadow nestled in the Western Himalayas. It is renowned for its diverse and vibrant floral carpet, showcasing a wide array of Himalayan flowers and rare plant species.",
    },
    "yamunotri": {
        "place": "Yamunotri",
        "state": "Uttarakhand",
		"hotels":"yamunotri cottages","blessing resort",
        "details": "Yamunotri, the source of the Yamuna River, is a significant pilgrimage destination in the Garhwal Himalayas. Pilgrims embark on the sacred Yamunotri Dham Yatra to visit the revered Yamunotri Temple and seek blessings.",
    },	

#telangana
    "adilabad": {
    "place": "Adilabad",
    "state": "Telangana",
    "places": "Kadam Dam, Basar Saraswathi Temple, Kuntala Waterfall, Jainath Temple",
    "hotels": "kakaku the guest house","hotel sai panchavati","hotel radhe krishna",
    "details": "Adilabad is a district in the northern part of Telangana, known for its scenic landscapes, rivers, and cultural heritage. The Godavari, Penganga, and Pranahita rivers flow through the district, contributing to its agricultural prosperity. Adilabad is also home to various tourist attractions, including the picturesque Kadam Dam, the spiritual Basar Saraswathi Temple, the stunning Kuntala Waterfall, and the ancient Jainath Temple. The district offers a mix of natural beauty and cultural richness, making it an interesting destination for travelers."
    },
"bhadrachalam": {
    "place": "Bhadrachalam",
    "state": "Telangana",
    "places":"Sri Sitaramachandra Swamy Temple","Parnasala","Abhaya Anjaneya Temple","Godavari River Ghats",
    "details": "Bhadrachalam is a town in the Khammam district of Telangana, situated on the banks of the Godavari River. It is renowned for the Sri Sitaramachandra Swamy Temple dedicated to Lord Rama. The town holds cultural and religious significance, attracting devotees and tourists alike. Major festivals celebrated include Sri Rama Navami and Vaikunta Ekadashi. Tourist attractions in and around Bhadrachalam include the famous Sri Sitaramachandra Swamy Temple, Parnasala (associated with Lord Rama's exile), Abhaya Anjaneya Temple, and the scenic Godavari River Ghats.",
    },
"hyderabad": {
    "place": "Hyderabad",
    "state": "Telangana",
    "places":"Charminar","Golconda Fort","Qutb Shahi Tombs","Hussain Sagar Lake","Birla Mandir","Salar Jung Museum",
	"hotels":"Luxury Haven Hotel","Royal Residency Suites","Cityscape Grand Hotel","Hyderabad Marriott Plaza","Tech Park Inn & Suites",
    "details": "Hyderabad, the capital city of Telangana, is located on the Deccan Plateau. Known for its rich history, cultural heritage, and vibrant cuisine, Hyderabad is a major center for technology and business. The city is famous for landmarks like Charminar and Golconda Fort, and it's renowned for its delicious biryani. Hyderabad is multilingual, with people speaking Telugu, Urdu, and English. Major districts include Hyderabad and Secunderabad. The city's economy is driven by industries such as Information Technology, Biotechnology, and Pharmaceuticals.",
    },
"khammam": {
    "place": "Khammam",
    "state": "Telangana",
    "places":"Khammam Fort","Kinnerasani Dam","Parnasala","Kusumanchi","Bhadrachalam",
    "details": "Khammam is a district in the southern part of Telangana, known for its historical sites, natural beauty, and cultural heritage. The district includes major towns like Khammam, Sathupally, and Kothagudem. The Godavari and Munneru rivers flow through the region, contributing to its agricultural prosperity. Khammam is home to attractions like Khammam Fort, Kinnerasani Dam, and Parnasala. The economy is driven by agriculture, coal mining, and power generation.",
    },
"kinnersani_wildlife_sanctuary": {
    "place": "Khammam District, Telangana",
    "places":"Kinnerasani Dam","Palair Reservoir","Jalagam Vengal Rao Park","Kusumanchi",
    "details": "Kinnerasani Wildlife Sanctuary is located in the Khammam District of Telangana, established in 1952. The sanctuary covers an area of 635.4 square kilometers and is known for its diverse flora and fauna. The vegetation includes teak, bamboo, terminalia, and pterocarpus. The sanctuary is home to various wildlife species, including tigers, leopards, sloth bears, sambar deer, and nilgai. Birdwatchers can spot species like peafow",
	},
"laknavaram_lake": {
    "place": "Warangal Rural District, Telangana",
	"places":"haritha resort island",hammock island","boating",
    "details": "Laknavaram Lake is a stunning man-made reservoir located in the Warangal Rural District of Telangana. Covering an expansive area of 10,000 acres, the lake is known for its picturesque islands and lush greenery. The lake has connected islands, including the Haritha Resort Island, Campsites Island, and Hammock Island. Visitors can engage in activities such as boating, island hopping, nature walks, and camping. The surroundings feature bamboo groves and palm trees, providing a serene and scenic environment. The lake is home to various bird species, making it a popular destination for nature enthusiasts and those seeking a peaceful getaway.",
	},
"medak_cathedral": {
    "place": "Medak, Telangana",
	"places":"medak fort","singur dam","Edupayala Vana Durga Bhavani Temple","Kondapur Archaeological Museum",
    "details": "The Medak Cathedral, located in Medak, Telangana, is a prominent religious landmark. Constructed in the Gothic Revival style, the cathedral stands as the single largest monolithic church in South India. It was consecrated in 1924 and features stunning architecture, including stained glass windows that depict various biblical scenes. The cathedral's bell tower is noteworthy, housing a carillon of 56 bells. The Medak Cathedral is not only a place of worship but also a site of architectural and historical significance, attracting visitors from near and far.",
	},
"medaram": {
    "place": "Medaram, Telangana",
    "places":"medaram village","Eturnagaram Wildlife Sanctuary","Pochera Waterfall",
	"hotels":"varshitha homes","haritha grand hotel",
    "details":"Medaram is a remote place in the Eturnagaram Wildlife Sanctuary, a part of Dandakaranya, the largest surviving forest belt in the Deccan. Once declared a national festival, the jatara can be considered for 'intangible cultural heritage of humanity' tag of UNESCO.",
	},
"nagarjuna_sagar": {
    "place": "Nagarjuna Sagar, Telangana",
    "places":"Ethipothala Waterfall","Nagarjuna Konda Island and Museum","Anupu (Ancient Buddhist site)","Srisailam Wildlife Sanctuary",
    "details": "Nagarjuna Sagar is a prominent tourist destination in Telangana, known for the Nagarjuna Sagar Dam, one of the largest dams in Asia. The dam has been a significant contributor to irrigation, hydroelectricity, and drinking water supply to the region. Nagarjuna Konda Island, formed by the dam, houses the Nagarjuna Konda Museum, showcasing relics from the ancient Buddhist civilization. Other attractions include the Ethipothala Waterfall, Anupu (an ancient Buddhist site),
    },
"nalgonda": {
    "place": "Nalgonda, Telangana",
    "places":"Panagal Reservoir","Devarakonda Fort","Bhongir Fort","Temples (Various locations)","Suryapet",
	"hotels":"hotel manorama","swagath residency","hotel vivera",
	"details":"Nalgonda is a district in the southern part of Telangana. The name has been derived from two Telugu words namely Nalla (Black) & Konda (Hill). Nalgonda was earlier called Neelagiri by Rajput rulers and later it was known as Nallagonda following the conquest by Bahamani king, Allauddin Bahaman Shah.",
	},
"nelakondapalli": {
    "place": "Nelakondapalli, Khammam district, Telangana",
	"places":" "Nelakondapalli Museum","Nelakondapalli Stupa","Archaeological Sites (Ikshvaku dynasty remains)",
	"details":"Nelakondapalli was a major town in ancient history. This is evidenced by one of the largest Buddhist stupas discovered in the Deccan (Dakhina, Dakhinapatha) region about 2 kilometers northeast of the contemporary village location, along with Satavahana era sites scattered around the village.",
	},
"nizamabad": {
    "place": "Nizamabad, Telangana",
    "places":"Nizamabad Fort","Alisagar Reservoir","Sarangapur Hanuman Temple","Pocharam Wildlife Sanctuary","Archaeological and Heritage Museum",
	"hotels":"hotel TRP BLISS","hotel lahari international","SP grand hotel",
    "details":"The District derived its name as Nizamabad (Nizam-a-abadi) from the Nizam of Hyderabad Asaf Jahi, VI who had ruled Deccan during the 18th Century A.D.",
	},
    "papikondalu": {
        "place": "Papikondalu",
        "state": "Telangana",
        "places": "Perantapalli, Pattiseema, Gandipochamma Temple, Papikondalu Scenic Hills",
        "hotels": "Papikondalu Bamboo Huts, Riverside Resorts",
        "details": "Papikondalu is a scenic hill range in the Godavari River, located in the state of Telangana, India. Known for its breathtaking landscapes, lush greenery, and the Godavari River flowing through the hills, Papikondalu is a popular tourist destination. The journey through Papikondalu offers picturesque views and is often done by boat rides. Visitors can explore attractions like Perantapalli, Pattiseema, Gandipochamma Temple, and enjoy a serene stay in bamboo huts or riverside resorts.",
    },
    "secunderabad": {
        "place": "Secunderabad",
        "state": "Telangana",
        "places": "Trimulgherry Fort, St. Mary's Church, Hussain Sagar Lake, Rashtrapati Nilayam",
        "hotels": "Taj Falaknuma Palace, The Manohar, Marriott Hotel Hyderabad",
        "details": "Secunderabad is a twin city of Hyderabad in the Indian state of Telangana. Known for its rich history and modern developments, Secunderabad offers a mix of cultural and contemporary experiences. Visitors can explore historical sites like Trimulgherry Fort and St. Mary's Church, enjoy the serene Hussain Sagar Lake, and visit Rashtrapati Nilayam, the official retreat residence of the President of India. The city also boasts a range of hotels, including luxurious options like Taj Falaknuma Palace and Marriott Hotel Hyderabad.",
    },
    "warangal": {
        "place": "Warangal",
        "state": "Telangana",
        "places": "Warangal Fort, Thousand Pillar Temple, Bhadrakali Temple, Kakatiya Kala Thoranam",
        "hotels": "The Gateway Hotel, Suprabha Hotel, Ashoka Hotel",
        "details": "Warangal, located in the heart of Telangana, is a city with a rich historical and cultural heritage. The Warangal Fort, Thousand Pillar Temple, Bhadrakali Temple, and Kakatiya Kala Thoranam are some of the prominent attractions that showcase the city's glorious past. The Thousand Pillar Temple is renowned for its exquisite architecture. Visitors can explore the majestic Warangal Fort, dedicated to the Kakatiya dynasty. The city offers a variety of accommodation options, including The Gateway Hotel, Suprabha Hotel, and Ashoka Hotel.",
    }

#sikkim
    "gangtok": {
        "place": "Gangtok",
        "state": "Sikkim",
        "places": "Nathula Pass, Tsomgo Lake, Rumtek Monastery, Enchey Monastery",
        "hotels": "Mayfair Spa Resort & Casino, The Elgin Nor-Khill, Summit Golden Crescent Resort & Spa",
        "details": "Gangtok, the capital city of Sikkim, is nestled in the eastern Himalayan range. The city is known for its stunning landscapes, vibrant culture, and Buddhist monasteries. Visitors can explore attractions like Nathula Pass, a high-altitude mountain pass near the Indo-China border, and Tsomgo Lake, a serene glacial lake surrounded by mountains. The city is dotted with monasteries such as Rumtek Monastery and Enchey Monastery, offering a glimpse into the region's spiritual heritage. Accommodation options in Gangtok include luxurious resorts like Mayfair Spa Resort & Casino, The Elgin Nor-Khill, and Summit Golden Crescent Resort & Spa.",
    },
    "goecha_la": {
        "place": "Goecha La",
        "state": "Sikkim",
        "places": "Goecha La Pass, Kanchenjunga National Park, Samiti Lake",
        "hotels": "Accommodation in nearby towns and base camps",
        "details": "Goecha La is a high mountain pass in the state of Sikkim, offering breathtaking views of the Himalayas, including the majestic Kanchenjunga. It is a popular trekking destination for adventure enthusiasts. The trek takes you through the pristine Kanchenjunga National Park, where you can witness diverse flora and fauna. The Goecha La Pass itself provides panoramic views of snow-capped peaks. Along the trek, you'll encounter stunning sites like Samiti Lake. Accommodations are generally available in nearby towns and base camps for trekkers.",
    },
    "gurudongmar_lake": {
        "place": "Gurudongmar Lake",
        "state": "Sikkim",
        "places": "Gurudongmar Lake, Chopta Valley, Thangu Valley",
        "hotels": "Accommodation in nearby towns and villages",
        "details": "Gurudongmar Lake is one of the highest lakes in the world, located in the northern part of Sikkim. Surrounded by snow-capped mountains, the lake is considered sacred by both Buddhists and Sikhs. Visitors can enjoy the breathtaking views of the lake and the surrounding landscapes. Chopta Valley and Thangu Valley are nearby attractions known for their pristine beauty. Due to the high altitude, it is recommended to acclimatize properly before visiting. Accommodations are available in nearby towns and villages for travelers.",
    },
    "kanchenjunga_national_park": {
        "place": "Kanchenjunga National Park",
        "state": "Sikkim",
        "places": "Kanchenjunga, Goecha La, Green Lake, Yumthang Valley",
        "hotels": "Accommodation in nearby towns and villages",
        "details": "Kanchenjunga National Park, located in the state of Sikkim, is a UNESCO World Heritage Site and home to the third-highest mountain in the world, Mount Kanchenjunga. The park is known for its diverse flora and fauna, including red pandas, Himalayan tahr, and various species of orchids. Popular trekking destinations within the park include Goecha La and Green Lake, offering stunning views of the Himalayan peaks. Yumthang Valley, famous for its colorful flowers, is also a notable attraction. Travelers can find accommodation in nearby towns and villages while exploring the natural beauty of the national park.",
    },
    "lachen": {
        "place": "Lachen",
        "state": "Sikkim",
        "places": "Gurudongmar Lake, Chopta Valley, Thangu Valley",
        "details": "Lachen is a picturesque town in North Sikkim known for its stunning landscapes and proximity to high-altitude lakes and valleys. It serves as a base for exploring places like Gurudongmar Lake, one of the highest lakes in the world. Chopta Valley and Thangu Valley are nearby attractions with breathtaking scenery. Lachen itself is surrounded by snow-capped mountains and offers a tranquil environment. Travelers can find accommodation options within Lachen to enjoy the natural beauty and embark on excursions to the nearby attractions.",
    },
    "lachung": {
        "place": "Lachung",
        "state": "Sikkim",
        "places": "Yumthang Valley, Zero Point, Lachung Monastery, Shingba Rhododendron Sanctuary",
        "details": "Lachung is a charming village in North Sikkim, known for its scenic beauty and proximity to some of the region's most beautiful attractions. Yumthang Valley, often referred to as the 'Valley of Flowers,' is a major highlight with its colorful blooms. Zero Point, offering panoramic views of snow-capped mountains, is another must-visit destination. Lachung Monastery and Shingba Rhododendron Sanctuary showcase the cultural and natural richness of the area. Accommodation options are available in Lachung, providing a comfortable stay for visitors exploring the picturesque surroundings.",
    },
    "nathula_pass": {
        "place": "Nathula Pass",
        "state": "Sikkim",
        "places": "Baba Harbhajan Singh Temple, Tsomgo Lake, Old Baba Mandir",
		"hotels":"namdul retreat",tasiling residency hotel and spa",
        "details": "Nathula Pass is a high-altitude mountain pass in the Himalayas, connecting India and China. It is located in the state of Sikkim and offers breathtaking views of the surrounding landscapes. Visitors can explore nearby attractions such as Baba Harbhajan Singh Temple, a shrine dedicated to an Indian Army soldier, and Tsomgo Lake, a glacial lake known for its scenic beauty. The Old Baba Mandir is another notable site in the region. Due to its high altitude, it is advisable to acclimatize properly before visiting Nathula Pass. Accommodations are generally available in nearby towns and base camps for travelers.",
    },
    "north_sikkim": {
        "region": "North Sikkim",
        "state": "Sikkim",
        "places": "Lachung, Lachen, Gurudongmar Lake, Yumthang Valley, Zero Point, Thangu Valley",
        "hotels": "Udaan hotels,kaya gantavya resort and spa",
        "details": "North Sikkim is a breathtaking region known for its pristine landscapes and high-altitude destinations. Lachung and Lachen are picturesque villages serving as gateways to several attractions. Gurudongmar Lake, one of the highest lakes in the world, offers stunning views. Yumthang Valley, known as the 'Valley of Flowers,' is famous for its colorful blooms. Zero Point provides panoramic views of snow-capped mountains. Thangu Valley is another beautiful destination in the region. Accommodations are available in Lachung and Lachen, providing visitors with comfortable stays while exploring the natural beauty of North Sikkim.",
    },
    "rumtek_monastery": {
        "place": "Rumtek Monastery",
        "state": "Sikkim",
        "places": "Rumtek Monastery, Golden Stupa, Nalanda Institute",
        "hotels": "the golden crest hotel","sterling gangtok orange village","MAYFAIR spa and resort",
        "details": "Rumtek Monastery, also known as the Dharma Chakra Centre, is a Tibetan Buddhist monastery located near Gangtok, the capital of Sikkim. It is one of the most significant monasteries in the region and serves as the seat of the Karmapa, the head of the Kagyu sect. The monastery complex includes the main Rumtek Monastery, the Golden Stupa, and the Nalanda Institute. Visitors can explore the vibrant murals, intricate artwork, and the serene ambiance of the monastery. Accommodations are available in nearby areas for those wanting to experience the spiritual and cultural richness of Rumtek Monastery.",
    },
    "south_sikkim": {
        "region": "South Sikkim",
        "state": "Sikkim",
        "places": "Namchi, Ravangla, Temi Tea Garden, Samdruptse Monastery, Siddheswar Dham, Tendong Hill",
        "hotels": "The temi bunglaow","sobralia hotels",
        "details": "South Sikkim is a captivating region known for its scenic beauty, cultural sites, and serene landscapes. Namchi, the capital of South Sikkim, is home to attractions like Siddheswar Dham, a pilgrimage site, and the towering statue of Guru Padmasambhava at Samdruptse Monastery. Ravangla is another charming town known for its peaceful atmosphere and the picturesque Temi Tea Garden. Tendong Hill offers panoramic views of the surrounding mountains and valleys. Accommodations are available in Namchi and Ravangla, providing a comfortable stay for visitors exploring the attractions of South Sikkim.",
    },
    "tsongmo_lake": {
        "place": "Tsongmo Lake",
        "state": "Sikkim",
        "places": "Baba Mandir, Nathula Pass, Kyongnosla Alpine Sanctuary",
        "hotels":"tempo heritage resort and spa","taj guras kutir resort and spa",
        "details": "Tsongmo Lake, also known as Changu Lake, is a glacial lake situated in East Sikkim. Surrounded by steep mountains and pristine beauty, the lake is a popular tourist destination. Visitors can enjoy the breathtaking scenery and may also visit nearby attractions like Baba Mandir, a revered shrine, and Nathula Pass, a high-altitude mountain pass. The Kyongnosla Alpine Sanctuary is another natural marvel in the vicinity. While there may not be direct accommodations at the lake, visitors can find lodging in nearby towns to experience the tranquility and beauty of Tsongmo Lake.",
    },
    "west_sikkim": {
        "region": "West Sikkim",
        "state": "Sikkim",
        "places": "Pelling, Yuksom, Khecheopalri Lake, Rabdentse Ruins, Singshore Bridge",
        "hotels": "Accommodation available in Pelling and Yuksom",
        "details": "West Sikkim is a mesmerizing region known for its lush green landscapes, historical sites, and cultural richness. Pelling, a popular town in the region, offers stunning views of the Himalayas and is known for attractions like Khecheopalri Lake, considered sacred. Yuksom, the historical capital of Sikkim, is known for its historical significance and serves as the starting point for the Goecha La trek. Rabdentse Ruins provide a glimpse into the history of the region. The Singshore Bridge is a scenic marvel. Accommodations are available in Pelling and Yuksom, providing visitors with a comfortable stay while exploring the wonders of West Sikkim.",
    },
    "yuksom": {
        "place": "Yuksom",
        "region": "West Sikkim",
        "state": "Sikkim",
        "places": "Dubdi Monastery, Norbugang Park, Tashiding Monastery, Khecheopalri Lake",
        "hotels": "hotel red palace","chungda hidden homestay","ejam residency",
        "details": "Yuksom, situated in West Sikkim, is a historic town and a popular base for trekking in the region. It was the first capital of Sikkim and holds cultural and historical significance. Visitors can explore attractions such as Dubdi Monastery, the oldest monastery in Sikkim, and Norbugang Park, which houses the Norbugang Chorten and the stone throne of the first Chogyal. Tashiding Monastery is another spiritual site with panoramic views. Khecheopalri Lake, considered sacred, is nearby. Accommodation options are available in and around Yuksom, providing a comfortable stay for those exploring the rich cultural and natural heritage of the area.",
    },
    "yumthang_valley": {
        "place": "Yumthang Valley",
        "region": "North Sikkim",
        "state": "Sikkim",
        "places": "Zero Point, Shingba Rhododendron Sanctuary, Yumthang Hot Springs",
        "hotels": "the country house","magellan's the golden bridge",
        "details": "Yumthang Valley, often referred to as the 'Valley of Flowers,' is a picturesque destination in North Sikkim. Surrounded by snow-capped mountains and lush greenery, the valley blooms with vibrant flowers during the spring season. Visitors can explore attractions such as Zero Point, offering panoramic views, and the Shingba Rhododendron Sanctuary, home to various species of rhododendrons. The Yumthang Hot Springs, known for their therapeutic properties, are another highlight. Accommodations are available in Lachung, serving as a base for exploring the enchanting beauty of Yumthang Valley.",
    },
    "zuluk": {
        "place": "Zuluk",
        "region": "East Sikkim",
        "state": "Sikkim",
        "places": "Thambi View Point, Lungthung, Nathang Valley, Kupup Lake, Old Baba Mandir",
        "hotels": "snow lion resort","eco log hut resort","club mahindra resort",
        "details": "Zuluk, situated in East Sikkim, is a quaint village known for its breathtaking landscapes and proximity to the Old Silk Route. Visitors can enjoy panoramic views from Thambi View Point and explore charming spots like Lungthung. Nathang Valley is a picturesque destination with vast meadows and stunning scenery. Kupup Lake, also known as Elephant Lake, and the Old Baba Mandir are other notable attractions in the region. Accommodation options are available in Zuluk, providing visitors with a comfortable stay while experiencing the tranquility and beauty of the area.",
    },
}

#odissha

    "baripada": {
        "place": "Baripada",
        "state": "Odisha",
        "places": "List of notable places or attractions",
        "hotels": "belgadia palace","ava guest house","tulsi guest house",
        "details": "General information about Baripada, its history, culture, or any other relevant details.",
    },
    "berhampur": {
        "place": "Berhampur",
        "state": "Odisha",
        "places": "maa tarini temple","aryapalli marine beach","ISCKON temple","ramlingeshwar park",
        "hotels": "hotel spectrum","hotel nandan international",
        "details": "General information about Berhampur, its history, culture, or any other relevant details.",
    },
    "bhubaneswar": {
        "place": "Bhubaneswar",
        "state": "Odisha",
        "places": " Lingaraj Temple"," Odisha State Museum"," Nandankanan Zoo",
        "hotels": "MAYFAIR lagoon","hello stay hotel","swosthi premium hotel",
        "details": "Bhubaneswar is the capital of Odisha and a city with rich historical and cultural significance. It is known for its ancient temples, vibrant festivals, and modern infrastructure. Notable places include the iconic Lingaraj Temple, the Odisha State Museum showcasing historical artifacts, and Nandankanan Zoo housing a variety of wildlife. Visitors can explore the city's unique blend of tradition and modernity. There are various accommodation options available in Bhubaneswar to suit different preferences and budgets.",
    },
    "chandipur": {
        "place": "Chandipur",
        "state": "Odisha",
        "places": "Chandipur Beach, Balaramgadi Beach, Panchalingeshwar Temple",
        "details": "Chandipur is a coastal town known for its unique phenomenon of the sea receding up to 5 kilometers during low tide and then returning during high tide. The pristine Chandipur Beach is a major attraction, providing a serene environment for visitors. Balaramgadi Beach is another beautiful spot known for its fishing activities. The Panchalingeshwar Temple, located on a hill near the sea, is a popular pilgrimage site. Accommodation options are available in Chandipur, offering a comfortable stay for those seeking to enjoy the coastal beauty of the region.",
    },
    "chilika_lake": {
        "place": "Chilika Lake",
        "state": "Odisha",
        "places": "Satapada, Kalijai Island, Nalabana Bird Sanctuary, Rambha",
		"hotel":"swosthi chilika resort","eco cottage chilika island resort:,
        "details": "Chilika Lake is the largest coastal lagoon in India, known for its biodiversity and scenic beauty. The lake is a haven for migratory birds, and Nalabana Bird Sanctuary is a significant part of the lake known for its avian population. Satapada is a popular gateway to Chilika Lake and offers boat rides to see dolphins. Kalijai Island is a small island in the lake with a revered temple dedicated to Goddess Kalijai. Rambha is another picturesque spot along the lake's shore. Chilika Lake is a Ramsar Wetland site and a must-visit destination for nature enthusiasts.",
    },
    "cuttack": {
        "place": "Cuttack",
        "state": "Odisha",
        "places": "Barabati Fort, Cuttack Chandi Temple, Odisha Maritime Museum, Netaji Birth Place Museum",
        "hotels": "grand residency hotel","pramod convention and club","hotel bombay inn",
        "details": "Cuttack, also known as the 'Silver City,' is a historic city in Odisha with a rich cultural and historical heritage. Barabati Fort is a centuries-old fort that stands as a testament to the city's history. The Cuttack Chandi Temple is a popular Hindu temple dedicated to Goddess Chandi. The Odisha Maritime Museum offers insights into the maritime history of the region. The Netaji Birth Place Museum is dedicated to the birthplace of Netaji Subhas Chandra Bose. Cuttack is known for its traditional silver filigree work and is a hub of cultural and economic activities in Odisha. There are various accommodation options available for visitors to experience the charm of Cuttack.",
    },
    "dhauli": {
        "place": "Dhauli",
        "state": "Odisha",
        "places": "Dhauli Shanti Stupa, Dhabaleswar Temple, Ashokan Edicts",
        "details": "Dhauli is a significant historical site located near Bhubaneswar in Odisha, known for its association with the Kalinga War and Emperor Ashoka's transformation. The Dhauli Shanti Stupa is a Buddhist monument built to promote peace and non-violence. The site also houses the Dhabaleswar Temple, dedicated to Lord Shiva. The Ashokan Edicts, inscribed on a rock, recount Ashoka's message of peace. Dhauli holds immense cultural and spiritual importance and attracts visitors interested in history and Buddhism.",
    },
    "gopalpur": {
        "place": "Gopalpur",
        "state": "Odisha",
        "places": "Gopalpur Beach, Rushikulya Beach, Berhampur Beach, Gopalpur Light House",
        "hotels": "gopalpur palm resort","zone by the park","mayfair palm beach resort",
        "details": "Gopalpur is a serene beach town in Odisha known for its pristine coastline and tranquil surroundings. Gopalpur Beach is the main attraction, offering a peaceful retreat and beautiful sunsets. Rushikulya Beach is known for its scenic beauty and is a nesting ground for Olive Ridley sea turtles. Berhampur Beach is another nearby spot for relaxation by the sea. The Gopalpur Light House provides panoramic views of the surroundings. The town is a perfect destination for those seeking a quiet beach holiday. Gopalpur offers various accommodation options for visitors to enjoy the coastal beauty of the region.",
    },
    "hirakud_dam": {
        "place": "Hirakud Dam",
        "state": "Odisha",
        "places": "Gandhi Minar, Nehru Minar, Hirakud Reservoir",
        "details": "Hirakud Dam is a major dam on the Mahanadi River, located in the state of Odisha. It is one of the longest dams in the world and plays a crucial role in irrigation, flood control, and power generation. The dam has created a vast reservoir known as the Hirakud Reservoir. Visitors can explore attractions like Gandhi Minar and Nehru Minar, which are memorials located on the dam. The site offers scenic views of the reservoir and is a significant engineering marvel in India.",
    },
    "jeypore": {
        "place": "Jeypore",
        "state": "Odisha",
        "places": "Jeypore Palace, Jagannath Sagar, Kolab Botanical Garden, Gupteshwar Cave Temple",
        "hotels": "balkrishna palace","udaya palce hotel","woods residency",
        "details": "Jeypore is a town in the Koraput district of Odisha, known for its cultural heritage and natural beauty. Jeypore Palace is a historical attraction that reflects the architectural grandeur of the past. Jagannath Sagar is a serene lake surrounded by greenery, offering a peaceful retreat. The Kolab Botanical Garden is a lush garden with diverse plant species. The Gupteshwar Cave Temple is a significant religious site dedicated to Lord Shiva. Jeypore provides a blend of history, nature, and spirituality for visitors. Accommodation options are available in Jeypore to make the stay comfortable for travelers exploring the region.",
    },
    "konark": {
        "place": "Konark",
        "state": "Odisha",
        "places": "Konark Sun Temple, Chandrabhaga Beach, Konark Museum",
        "hotels": "lotus eco resort","wilddunes",
        "details": "Konark is a town famous for the Konark Sun Temple, a UNESCO World Heritage Site and an architectural marvel. The Sun Temple is dedicated to the sun god Surya and is known for its intricate stone carvings and chariot-shaped architecture. Chandrabhaga Beach, located nearby, offers a serene coastal experience. The Konark Museum showcases sculptures and artifacts related to the history of the region. Konark is a significant pilgrimage and tourist destination, attracting visitors with its cultural and historical richness. Various accommodation options are available in Konark to cater to the needs of travelers exploring this historical town.",
    },
    "puri": {
        "place": "Puri",
        "state": "Odisha",
        "places": "Jagannath Temple, Puri Beach, Gundicha Temple, Chilika Lake",
        "hotels": "victoria club hotel","hotel royal grand heritage",
        "details": "Puri is a sacred city known for its rich cultural heritage and religious significance. The Jagannath Temple, dedicated to Lord Jagannath, is one of the Char Dham pilgrimage sites and a major attraction. Puri Beach is a popular destination for both pilgrims and tourists, offering a scenic view of the Bay of Bengal. The Gundicha Temple is associated with the Rath Yatra festival. Chilika Lake, Asia's largest brackish water lagoon, is located near Puri and is a haven for migratory birds. Puri is a vibrant city that attracts devotees, beach lovers, and nature enthusiasts. There are various accommodation options in Puri catering to the diverse preferences of visitors.",
    },
    "rourkela": {
        "place": "Rourkela",
        "state": "Odisha",
        "places": "Rourkela Steel Plant, Hanuman Vatika, Mandira Dam, Vedvyas Temple",
        "details": "Rourkela is a well-planned industrial city known for the Rourkela Steel Plant, one of the largest steel plants in India. Hanuman Vatika is a prominent temple complex dedicated to Lord Hanuman and is a popular religious site. Mandira Dam, located on the Mandira Reservoir, offers a serene environment for picnics and relaxation. Vedvyas Temple, situated on the confluence of rivers Koel, Sankha, and Saraswati, is a significant pilgrimage site. Rourkela combines industrial prowess with natural beauty, making it a diverse destination for visitors. Various accommodation options are available in Rourkela to cater to the needs of travelers.",
    },
    "talasari_beach": {
        "place": "Talasari Beach",
        "state": "Odisha",
        "places": "Talasari Beach, Udaipur Beach, Chandaneswar Temple",
        "details": "Talasari Beach is a hidden gem located in the Baleswar district of Odisha. Known for its pristine and less-explored beauty, the beach offers a tranquil escape for nature lovers. Udaipur Beach, an extension of Talasari, adds to the scenic charm. Visitors can enjoy long stretches of golden sands and the calming sound of the waves. Chandaneswar Temple, dedicated to Lord Shiva, is a nearby religious attraction. Talasari Beach is ideal for those seeking a peaceful and secluded beach experience away from the crowds.",
    },
    "tikarapada_wildlife_sanctuary": {
        "place": "Tikarapada Wildlife Sanctuary",
        "state": "Odisha",
        "places": "Tikarapada Dam, Satkosia Gorge, Mahanadi River",
        "details": "Tikarapada Wildlife Sanctuary is a haven for nature and wildlife enthusiasts, situated along the banks of the Mahanadi River. The sanctuary is known for its diverse flora and fauna, providing a natural habitat for various species. Tikarapada Dam and Satkosia Gorge offer stunning views of the landscape. Visitors can enjoy boat rides on the Mahanadi River to explore the sanctuary and spot wildlife. The sanctuary is particularly known for its rich avian population. Tikarapada is a peaceful retreat for those seeking a close encounter with nature and wildlife in a serene environment.",
    },
    "udaygiri_khandagiri_caves": {
        "place": "Udaygiri and Khandagiri Caves",
        "state": "Odisha",
        "places": "Udaygiri Caves, Khandagiri Caves, Hathi Gumpha, Ananta Cave, Rani Gumpha",
		"hotels":"hotel SJ pride","the greenstar inn premium",
        "details": "Udaygiri and Khandagiri Caves are ancient Jain rock-cut caves situated on two adjacent hills in Bhubaneswar. Udaygiri has 18 caves, and Khandagiri has 15 caves, each with unique historical and architectural significance. The caves are adorned with intricate carvings and inscriptions. Hathi Gumpha (Elephant Cave) is one of the prominent caves known for its detailed carvings. Ananta Cave and Rani Gumpha are other notable caves with interesting features. These caves provide insights into Jain ascetic life and are important archaeological and historical sites in Odisha.",
    },

#tripura
    "agartala": {
        "place": "Agartala",
        "state": "Tripura",
        "places": "Ujjayanta Palace, Neermahal, Tripura Sundari Temple, Sepahijala Wildlife Sanctuary",
        "hotels": "hotel polo towers,","hotel welcome palace","hotel sonari tori",
        "details": "Agartala is the capital city of Tripura, known for its cultural heritage and natural beauty. Ujjayanta Palace, the former royal palace, is a key attraction with its beautiful architecture and gardens. Neermahal, located in the middle of Rudrasagar Lake, is a stunning water palace. Tripura Sundari Temple is a significant pilgrimage site dedicated to Goddess Tripura Sundari. The Sepahijala Wildlife Sanctuary offers a glimpse of the region's biodiversity. Agartala provides a mix of historical, cultural, and natural attractions, making it a captivating destination. Various accommodation options are available in Agartala for visitors to explore the beauty of Tripura's capital.",
    },
    "ambassa": {
        "place": "Ambassa",
        "state": "Tripura",
        "places": "Siphahijla Wildlife Sanctuary","Jagannath Temple","Unakoti","Dumboor Lake"," Pilak","ChabimuraRosevalley National Park"," Tripurasundari Temple,",
        "hotels": "hotel grand zuri","A.R.hotel",
        "details": "General information about Ambassa, its history, culture, or any other relevant details.",
    },
    "bison_national_park": {
        "name": "Bison National Park",
        "state":"tripura",
        "places":"Bison Viewing Points", "Nature Trails", "Educational Programs",
        "hotels":"Wilderness Lodge", "Nature Retreat Hotel", "Bison Park Resort",
        "details": "Bison National Park is renowned for its diverse wildlife, including the Indian Bison. The park offers breathtaking scenic views, nature trails, and exciting wildlife safari opportunities. Visitors can stay in comfortable hotels within or near the park. It's an ideal destination for nature enthusiasts and wildlife lovers.",
    },
    "kailashshar": {
        "name": "Kailashshar",
        "state": "tripura",
        "places":"Kailash Temple", "Shivling Lake", "Adventure Park",
        "hotels":"Divine Retreat", "Mountain View Lodge", "Serene Heights Hotel",
        "details": "The distance of the Town from the capital Agartala is about 136.8 km. The Town shares a 320.46 km long international border with Bangladesh. Kailashahar is elevated by 28.36 meters from sea level. The Town is surrounded by Unkoti hills and Tripura's longest river, the Manu, flows through the Town into Bangladesh.",
    },
    "neermahal": {
        "name": "Neermahal",
        "state": "Tripura",
        "places":"Rudrasagar Lake", "Sipahijala Wildlife Sanctuary", "Tripura Sundari Temple",
        "hotels":"Lakeview Resort", "Palace Retreat", "Waterfront Lodge",
        "details": "Neermahal, the 'Water Palace,' is an architectural marvel situated on the scenic Rudrasagar Lake in Tripura. Known for its unique design and floating appearance, Neermahal is a popular tourist attraction. Visitors can explore the palace and enjoy the serene surroundings of Rudrasagar Lake. Nearby attractions include the Sipahijala Wildlife Sanctuary and the Tripura Sundari Temple. Accommodation options like Lakeview Resort, Palace Retreat, and Waterfront Lodge provide a comfortable stay for those exploring the beauty of Neermahal and its surroundings.",
    },
    "rudrasagar": {
        "name": "Rudrasagar",
        "state": "Tripura",
        "places":"Neermahal", "Sipahijala Wildlife Sanctuary", "Tripura Sundari Temple",
        "details": "Rudrasagar is a picturesque lake located in Tripura, known for its natural beauty and tranquility. The lake is home to the iconic Neermahal, a floating water palace that adds to the scenic charm. Visitors can enjoy boat rides on Rudrasagar and explore the serene surroundings. Nearby attractions include the Sipahijala Wildlife Sanctuary and the Tripura Sundari Temple. Rudrasagar is an ideal destination for those seeking a peaceful retreat, engaging in boating, and enjoying the natural beauty of the region.",
    },
    "unakoti": {
        "name": "Unakoti",
        "state": "Tripura",
        "places":"Gigantic Shiva Head", "Ashtashilalekh", "Waterfall",
        "hotel":"unakoti tourist lounge","loknath guest house",
        "details": "Unakoti is an ancient pilgrimage site in Tripura, known for its rock-cut carvings and sculptures. The site features a gigantic head of Lord Shiva, known as the 'Unakotiswara Kal Bhairava.' Ashtashilalekh, a group of carved images, and a nearby waterfall are also prominent attractions. Unakoti is a significant destination for pilgrims and history enthusiasts, offering a blend of religious and historical exploration. Visitors can engage in activities like pilgrimage, historical exploration, and nature walks while enjoying the unique artistry of Unakoti.",
    },

#nagaland
    "dimapur": {
        "name": "Dimapur",
        "state": "Nagaland",
        "places":"Kachari Ruins", "Dimapur Jain Temple", "Triple Falls",
        "hotels": "Heritage Hotel", "City Comfort Hotel", "Green Valley Inn",
        "details": "Dimapur is the largest city in Nagaland, known for its historical sites and vibrant culture. The Kachari Ruins showcase ancient structures, while the Dimapur Jain Temple reflects the city's religious diversity. Triple Falls is a scenic natural attraction. Visitors can stay in comfortable hotels like Heritage Hotel, City Comfort Hotel, and Green Valley Inn. Dimapur offers a range of activities, including exploring historical sites, shopping in local markets, and experiencing the rich cultural heritage of Nagaland.",
    },
    "dzukou_valley": {
        "name": "Dzukou Valley",
        "state": "Nagaland",
        "places": ["Dzukou Lily", "Japfu Peak", "Dzukou River"],
        "details": "Dzukou Valley is a breathtaking valley in Nagaland, near Kohima. Known for its lush greenery and flower-filled meadows, it is a paradise for trekkers. The valley is famous for the Dzukou Lily and offers stunning views of Japfu Peak and the Dzukou River. Popular activities include trekking, camping, and photography, making Dzukou Valley a must-visit destination for nature enthusiasts.",
    },
    "japfu_peak": {
        "name": "Japfu Peak",
        "state": "Nagaland",
        "places": ["Gurudwara on Japfu Peak", "Dzukou Valley", "Wildlife"],
        "details": "Japfu Peak is the second-highest peak in Nagaland, located near Kohima. The peak offers panoramic views of the surrounding landscapes, including the lush Dzukou Valley. Visitors can explore the diverse flora, spot wildlife, and visit the Gurudwara on Japfu Peak. Popular activities include trekking, spiritual retreats, and nature exploration, providing a unique experience for those seeking adventure and tranquility.",
    },
    "khonoma_village": {
        "name": "Khonoma Village",
        "state": "Nagaland",
        "places":"Khonoma Fort", "Dzuleke", "War Cemetery",
        "hotels":"dovipie inn","hills view cottage","alder cottage",
        "details": "Khonoma Village is a historic village near Kohima, known for its rich cultural heritage and conservation efforts. The village features the well-preserved Khonoma Fort and offers insights into the Naga way of life. Nearby attractions include Dzuleke and the War Cemetery. Visitors can engage in village walks, cultural experiences, and nature trails. Khonoma Village is a unique destination that reflects the traditions and environmental consciousness of the Naga people.",
    },
    "kohima": {
        "name": "Kohima",
        "state": "Nagaland",
        "places":"Kohima War Cemetery", "Kohima State Museum", "Kisama Heritage Village",
        "hotels":"Heritage Inn", "Kohima Camp", "Hotel Japfü",
        "details": "Kohima, the capital city of Nagaland, is a cultural hub with historical significance and natural beauty. The Kohima War Cemetery commemorates the World War II Battle of Kohima. The Kohima State Museum showcases Naga artifacts, and the Kisama Heritage Village offers insights into Naga culture. Visitors can engage in activities like exploring Naga culture, visiting historical sites, and enjoying nature walks. Various hotels, including Heritage Inn, Kohima Camp, and Hotel Japfü, provide accommodation options for a comfortable stay in Kohima.",
    },
    "mokokchung": {
        "name": "Mokokchung",
        "state": "Nagaland",
        "places":"Longkhum Village", "Mokokchung District Museum", "Changkikong Range",
        "hotels":"Tragopan Lodge", "Mokokchung Metropol Hotel", "Whispering Winds",
        "details": "Mokokchung is a vibrant town in Nagaland, celebrated for its cultural richness and scenic beauty. It serves as an educational center and is a hub of the Ao Naga tribe. Attractions include Longkhum Village, known for its terraced fields, the Mokokchung District Museum, and the picturesque Changkikong Range. Activities in Mokokchung include exploring Ao Naga culture, visiting local markets, and embarking on nature excursions. Various hotels like Tragopan Lodge, Mokokchung Metropol Hotel, and Whispering Winds offer comfortable accommodations for visitors to Mokokchung.",
    },
    "naga_heritage_village": {
        "name": "Naga Heritage Village",
        "state": "Nagaland",
        "places":"Morungs (Youth Dormitories)", "Traditional Huts", "Cultural Performances",
        "hotels":"neeramaya retreats","la colline resorts",
        "details": "The Naga Heritage Village, located in Kisama near Kohima, is a cultural showcase of Naga tribal traditions. It features morungs (youth dormitories), traditional huts, and cultural performances. The village hosts events like the Hornbill Festival and Nagaland Statehood Day Celebrations, attracting visitors from around the world. Activities at the Naga Heritage Village include experiencing Naga culture, shopping for handicrafts, and attending cultural events, providing a unique and immersive cultural experience.",
    },
    "pfutero": {
        "place": "Pfutero",
        "state": "nagaland",
        "places":"glory peak","phek",
        "details": "About 22,800 results (0.34 seconds)Pfütsero is a town located in the Phek District of the Indian state of Nagaland. It is the highest-altitude town and the coldest inhabited place in Nagaland with temperatures occasionally dropping below 0 °C during winter nights",
    },
    "shilloi_lake": {
        "place": "Shilloi Lake",
        "state": "Nagaland",
        "places":"Changtongya Village", "Naganimora", "Doyang River",
        "hotels":"hotel shilloi_lake","fairmont",
        "details": "Shilloi Lake is located in Lütsam Village of Phokhungri area under the Meluri sub-division in Phek district. There are many legends associated with the lake. One of them being that a baby was found floating in the middle of the lake and two hands were seen bobbing the baby.",
    },
    "touphema_village": {
        "place": "Touphema Village",
        "state": "Nagaland",
        "places":"Morungs (Youth Dormitories)", "Naga Cultural Performances", "Handloom and Handicraft Center",
        "hotels": "Village Stay Cottages", "Heritage Homestay", "Cultural Inn",
        "details": "Touphema Village, located near Kohima in Nagaland, is dedicated to preserving Naga culture. The village features traditional huts, morungs (youth dormitories), and hosts Naga cultural performances. Visitors can engage in village walks, cultural experiences, and shopping for authentic Naga handicrafts at the Handloom and Handicraft Center. Accommodation options like Village Stay Cottages, Heritage Homestay, and Cultural Inn offer a unique stay immersed in the local culture.",
    },
    "tuensang": {
        "place": "Tuensang",
        "state": "Nagaland",
        "places":"Chilise Village", "Lungwa Village", "Naganimora",
        "hotels": "Tuensang Heights", "Heritage Lodge", "Mountain View Hotel",
        "details": "Tuensang, located in Nagaland, is known for its cultural diversity, scenic landscapes, and vibrant local markets. The district boasts attractions like Chilise Village, Lungwa Village, and Naganimora. Visitors can engage in activities such as exploring tribal culture, nature excursions, and shopping in local markets. Tuensang offers accommodation options like Tuensang Heights, Heritage Lodge, and Mountain View Hotel for a comfortable stay amidst the natural beauty of the region.",
    },
}
	
	
	
